[package]
name = "entity"
version = "0.1.0"
edition = "2024"

[dependencies]
#sea-orm = { version = "1.1.8", features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
#serde = { version = "1.0.219", features = ["derive"] }


sea-orm = { workspace = true }
serde = { workspace = true }