//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::class::Entity as Class;
pub use super::class_course::Entity as ClassCourse;
pub use super::course::Entity as Course;
pub use super::student::Entity as Student;
